version: "3"
services:
  flask_app:
    build: .
    env_file:
      - .env  # Load environment variables from .env file
    ports:
      - "5000:5000"
    volumes:
      - ./instance:/app/instance  # Persistent storage for SQLite
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production
      - SECRET_KEY=4f3c9b0d1f5a6e2a8b7c9d0e1f3a5b6c7d8e9f0a1b2c3d4e5f6a7b8c9d0e1f2
